#!/bin/bash
#sin

RED=$(tput setaf 1) 
GREEN=$(tput setaf 2) 
CYAN=$(tput setaf 6) 
WHITE=$(tput setaf 7) 
begin=$(date +"%s")
chmod -R 777 ./

echo -e "${CYAN}
                            _    _ 
  /\  /\___ _ __  ___ _   _| | _(_)
 / /_/ / _ \ '_ \/ __| | | | |/ / |
/ __  /  __/ | | \__ \ |_| |   <| |
\/ /_/ \___|_| |_|___/\__,_|_|\_\_|
                  
                  - A Multivendor doujin grabber using Bash magic: 
                  0 API, 0 dependencies (formerly thru one-liner). - 2k19"
echo -e "${GREEN}"

PS3='type your vendor number or "6" to exit: '
options=("simply-hentai" "hentai2read" "nhentai" "nhensuki" "pururin" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "simply-hentai")
            cd bin;./hentai.sh
            ;;
        "hentai2read")
            cd bin;./h2r.sh
            ;;
        "nhentai")
            cd bin;./nhen.sh
            ;;
        "nhensuki")
            cd bin;./nhensuki.sh
            ;;
        "pururin")
            cd bin;./pur.sh
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done